swagger: "2.0"
info:
  title: Movies
  description: Movies API
  version: 1.0.0
host: localhost:9300
basePath: /api/v1
schemes:
  - http

tags:
  - name: Movies
    description: Movies API

paths: 
  /movies:
    get:
      tags:
        - all users 
      summary:
        Retrieve all users
      security : []
      responses:
        '200':
          description: Successful Operation
    
    post:
      tags:
        - create new user
      summary:
        create a new user
        
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful Operation
    
  /movies/:id:
    get:
      tags:
        - get a single user
      summary:
        Get a particular user
      security: []
      responses:
        '200':
          description: Successful Operation
    put:
      tags:
        - update a user's details
      summary:
        Update the profile of a user
      security: []
      responses: 
        '204':
          description: Successful Operation
    
    delete:
      tags:
        - delete a user's details
      summary:
        Delete the profile of a user
      security: []
      responses: 
        '204':
          description: Successful Operation
          
    patch:
      tags:
        - partially update  a user 
      summary:
        partially update a users details
      security: []
      responses:
        '204':
          description: Successful operation
      
      
      
      
      
      
      
      
      
      
      
      
      